<?php

$form = $this->form;
$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введите ваше имя'
]);
$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введите ваш email адрес',
]);
$form->get('text')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введите текст сообщения',
    'rows' => 6,
]);
$form->get('uploadedFile');
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

?>

<h1>Добавить запись</h1>

<p>
    Пожалуйста, заполните следующую форму и нажмите кнопку <i>Добавить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('text')); ?>
            <?= $this->formElement($form->get('text')); ?>
            <?= $this->formElementErrors($form->get('text')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('uploadedFile')); ?>
            <?= $this->formElement($form->get('uploadedFile')); ?>
            <?= $this->formElementErrors($form->get('uploadedFile')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>