<?php

$form = $this->form;
$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введите ваше имя'
]);
$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введите ваш email адрес',
]);
$form->get('text')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введите текст сообщения',
    'rows' => 6,
]);
$form->get('uploadedFile');
$form->get('status')->setAttributes([
    'class' => 'form-control'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

?>

<h1>Редактирование записи</h1>

<p>
    Пожалуйста, заполните следующую форму и нажмите кнопку <i>Сохранить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('text')); ?>
            <?= $this->formElement($form->get('text')); ?>
            <?= $this->formElementErrors($form->get('text')); ?>
        </div>

        <div class="form-group">
            <?php if($entry->getUploadedFile()): ?>
                <b>Файл прикреплен: </b> <?= $entry->getUploadedFile(); ?>
            <?php else: ?>
                <b>Файл не прикреплен
            <?php endif; ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('uploadedFile')); ?>
            <?= $this->formElement($form->get('uploadedFile')); ?>
            <?= $this->formElementErrors($form->get('uploadedFile')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>


        <p>
            <?= $this->formElement($form->get('submit')); ?>
            <a class="btn btn-default" href="
                <?= $this->url('guestbook', ['action'=>'admin']); ?>">
                Отмена
            </a>
        </p>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>